Repository alvr-org/PhoneVR, pull requests merged in 2020-08, with the labels that each got.

#12 Android: Upgrading Gradle version, adding library files for x86 suppo…
  code/.gitignore
  code/mobile/android/PhoneVR/app/CMakeLists.txt
  code/mobile/android/PhoneVR/app/src/main/res/values/styles.xml
  code/mobile/android/PhoneVR/build.gradle
  code/mobile/android/libraries/jni/x86/libgvr.so
  code/mobile/android/libraries/jni/x86/libgvr_audio.so
Labels: enhancement

#14 fixing compiler warnings
  code/common/libs/eigen/src/Core/arch/Default/BFloat16.h
  code/windows/PhoneVR/PhoneVR/PhoneVR.vcxproj
Labels: enhancement

#16 Android: Reverse Landscape orientation implemented
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Wrap.kt
Labels: feature

#15 Added app Signing configs, Androidx and CMake fixes
  appveyor.yml
  code/mobile/android/PhoneVR/app/PhoneVRKeyStore.jks
  code/mobile/android/PhoneVR/app/build.gradle
  code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/ExampleInstrumentedTest.kt
  code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/MainActivity.kt
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/SettingsActivity.kt
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Wrap.kt
  code/mobile/android/PhoneVR/app/src/main/res/layout/activity_main.xml
  code/mobile/android/PhoneVR/app/src/main/res/layout/activity_settings.xml
  code/mobile/android/PhoneVR/app/src/main/res/layout/content_main.xml
  code/mobile/android/PhoneVR/gradle.properties
  code/mobile/android/PhoneVR/gradle/wrapper/gradle-wrapper.properties
  code/mobile/android/PhoneVR/keystore.properties
Labels: enhancement, fix

#17 Windriver: Added a seperate Info Log
  code/common/src/PVRGlobals.cpp
  code/common/src/PVRGlobals.h
  code/windows/PhoneVR/PhoneVR/PVRFileManager.h
  code/windows/PhoneVR/PhoneVR/PVRGraphics.cpp
  code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
  code/windows/PhoneVR/PhoneVR/driver.cpp
Labels: feature

#18 Updated MainActivity, Troubleshooting tips, Defaulting pairing port
  README.md
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Globals.kt
  code/mobile/android/PhoneVR/app/src/main/res/layout/content_main.xml
  driver/bin/pvrsettings.json
Labels: enhancement

#19 Fixing FIle not Found Error on SteamVR
  README.md
  appveyor.yml
  code/windows/PhoneVR/PhoneVR/driver.cpp
Labels: enhancement

#20 Added Android Logging Debug|Release
  README.md
  code/common/src/PVRGlobals.cpp
  code/common/src/PVRGlobals.h
  code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/MainActivity.kt
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/SettingsActivity.kt
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Wrap.kt
  code/mobile/android/PhoneVR/app/src/main/res/layout/activity_settings.xml
  code/mobile/mobile-common/PVRSockets.cpp
Labels: enhancement, feature, fix

#21 [Win] Adding explicit backward compatibility
  code/windows/PhoneVR/PhoneVR/PhoneVR.vcxproj
Labels: enhancement

#22 [Doc Readme] Windriver streamsettings
  .github/LogoPVR.png
  .github/LogoPVRCotent.png
  README.md
  code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
Labels: documentation

#23 Feature: Complete FPS Stats on Android app
  .github/fps.jpg
  README.md
  code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Wrap.kt
  code/mobile/android/PhoneVR/app/src/main/res/layout/activity_game.xml
  code/mobile/mobile-common/PVRRenderer.cpp
  code/mobile/mobile-common/PVRRenderer.h
  code/mobile/mobile-common/PVRSockets.cpp
  code/mobile/mobile-common/PVRSockets.h
  code/windows/PhoneVR/PhoneVR/PVRGraphics.cpp
  code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
Labels: feature

#25 Show Average FPS instead of instantaneous
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
Labels: enhancement

#27 Added Timestamps to Android logs
  code/common/src/PVRGlobals.cpp
Labels: enhancement

#28 [Bug] SteamVR Headset Detection Issue Fix
  code/common/src/Utils/ThreadUtils.h
Labels: fix

#29 [Win] Added Extra Network info log messages
  code/common/src/PVRSocketUtils.cpp
  code/mobile/mobile-common/PVRSockets.cpp
  code/windows/PhoneVR/PhoneVR/driver.cpp
Labels: enhancement
