Repository alvr-org/PhoneVR, pull requests merged in 2021-01, with the labels that each got.

#53 Adding Error Handling in PVRGlobals & native-lib
  code/common/src/PVRGlobals.cpp
  code/common/src/Utils/ThreadUtils.h
  code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
  code/mobile/mobile-common/PVRRenderer.cpp
  code/mobile/mobile-common/PVRSockets.cpp
  code/mobile/mobile-common/Utils/RenderUtils.cpp
Labels: enhancement

#58 [Android] Error Handling OpenGL functions [RenderUtils.cpp]
  code/mobile/mobile-common/Utils/RenderUtils.cpp
Labels: enhancement

#57 [Andorid] Patch core network iffaddrs to fix Stack Corruption
  code/common/libs/ifaddrs/ifaddrs.c
Labels: fix

#59 [Android] Optimizing release build
  code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
  code/mobile/mobile-common/PVRRenderer.cpp
  code/mobile/mobile-common/PVRSockets.cpp
  code/mobile/mobile-common/Utils/RenderUtils.cpp
Labels: enhancement

#63 [Android] Network/Core fixes
  appveyor.yml
  code/common/libs/ifaddrs/LocalArray.h
  code/common/libs/ifaddrs/ScopedFd.h
  code/common/libs/ifaddrs/ifaddrs.c
  code/common/libs/ifaddrs/ifaddrs.h
  code/common/libs/ifaddrs/pvr_google_ifaddrs.h
  code/common/src/PVRSocketUtils.cpp
  code/mobile/android/PhoneVR/app/build-pr.gradle
  code/mobile/android/PhoneVR/app/build.gradle
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
  code/mobile/mobile-common/PVRSockets.cpp
  code/mobile/mobile-common/PVRSockets.h
  code/mobile/mobile-common/Utils/RenderUtils.cpp
  code/mobile/mobile-common/Utils/RenderUtils.h
  code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
  code/windows/PhoneVR/PhoneVR/driver.cpp
Labels: enhancement, fix

#65 [Android] Add ShareLogs and OpenLogs buttons
  code/mobile/android/PhoneVR/app/src/main/AndroidManifest.xml
  code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/SettingsActivity.kt
  code/mobile/android/PhoneVR/app/src/main/res/layout/activity_settings.xml
  code/mobile/android/PhoneVR/app/src/main/res/values/strings.xml
  code/mobile/android/PhoneVR/app/src/main/res/xml/provider_paths_app.xml
Labels: feature
